In [6]:
import numpy as np


def create_random_vectors(n: int, dim: int) -> np.array:
    np.random.seed(10)
    return np.random.random((n, dim)).astype("float32")

In [7]:
import faiss
import sys 
sys.path.append("/private/home/marialomeli/faiss_improvements/offline_ivf/")
from utils import find_all_divisors
# The input vector x is split into m distinct subvectors uj , 1 ≤ j ≤ m of dimension D∗ = D/m, 
# where D is a multiple of m. The subvectors are quantized separately using m distinct quantizers.

nb = 10000
dim = 768
xb=create_random_vectors(nb,dim)
# nbits has to be a divisor of the vector's dimensionality
all_nbits=find_all_divisors(dim)
print(all_nbits)
all_nbits_subset = [16]
for nbits in all_nbits_subset:
    codec = faiss.index_factory(dim, f"PQ{nbits}")
    codec.train(xb)

nq=100
#query vectors
xq=create_random_vectors(nq,dim)
# encode 
codes = codec.sa_encode(xq)

print(codes)

[1, 768, 2, 384, 3, 256, 4, 192, 6, 128, 8, 96, 12, 64, 16, 48, 24, 32]
[[236 148 122 ... 201 245  99]
 [ 32 187 178 ... 148 215 250]
 [ 23 156  92 ...  39 228 244]
 ...
 [146 138   8 ...  50 236  98]
 [ 18  88  96 ... 148 135 105]
 [225 214  41 ... 100 226  65]]
